-- CreateEnum
CREATE TYPE "NightlifePartyType" AS ENUM ('BAR_CRAWL', 'CLUBBING', 'LIVE_MUSIC', 'RAVE', 'THEMED_PARTY', 'KARAOKE_NIGHT', 'OPEN_MIC', 'COMEDY_SHOW', 'CASINO_NIGHT', 'SPEAKEASY', 'LOUNGE', 'ROOFTOP_PARTY', 'BEACH_PARTY', 'POOL_PARTY', 'BOAT_PARTY', 'DINNER_PARTY', 'PUB_QUIZ', 'JAZZ_NIGHT', 'SALSA_NIGHT', 'ELECTRONIC_DANCE_MUSIC', 'HIP_HOP_NIGHT', 'REGGAE_NIGHT', 'ROCK_NIGHT', 'LATIN_DANCE_NIGHT', 'VIP_EXPERIENCE', 'SILENT_DISCO', 'WINE_TASTING', 'COCKTAIL_PARTY', 'GAME_NIGHT', 'SPORTS_BAR_NIGHT', 'ART_EXHIBIT', 'FOOD_FESTIVAL');

-- CreateEnum
CREATE TYPE "NightlifeMusicTypes" AS ENUM ('HOUSE', 'TECHNO', 'TRANCE', 'EDM', 'DRUM_AND_BASS', 'DUBSTEP', 'HIP_HOP', 'RNB', 'POP', 'ROCK', 'METAL', 'REGGAE', 'LATIN', 'SALSA', 'MERENGUE', 'BACHATA', 'REGGAETON', 'KPOP', 'JPOP', 'AFROBEATS', 'DANCEHALL', 'DISCO', 'FUNK', 'JAZZ', 'BLUES');

-- CreateEnum
CREATE TYPE "BatchStatus" AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED');

-- CreateEnum
CREATE TYPE "BatchType" AS ENUM ('CLUB', 'EVENT');

-- CreateTable
CREATE TABLE "BatchAwaiter" (
    "id" TEXT NOT NULL,
    "batchId" TEXT NOT NULL,
    "batchStatus" "BatchStatus" NOT NULL DEFAULT 'PENDING',
    "batchType" "BatchType" NOT NULL DEFAULT 'CLUB',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BatchAwaiter_pkey" PRIMARY KEY ("id")
);
