const berlin = [
	{
		clubName: "Berghain",
		url: "https://berghain.berlin/events/",
		loadMoreSelector: null,
		singleEventSelector: ".event-item",
		mainContentSelectors: [],
	},
	{
		clubName: "Club der Visionäre",
		url: "https://clubdervisionaere.com/programm",
		loadMoreSelector: null,
		singleEventSelector: "#programmBox #programmC.clearfix div.clearfix",
		mainContentSelectors: [],
	},
	{
		clubName: "Tresor Berlin",
		url: "https://tresorberlin.com/events/",
		loadMoreSelector: null,
		singleEventSelector: ".event-item",
		mainContentSelectors: [],
	},
	{
		clubName: "Zur wilden Renate",
		url: "https://www.renate.cc/",
		loadMoreSelector: null,
		singleEventSelector:
			".acc-content.sub-accordion .program-accordion .prog-row",
		mainContentSelectors: [],
	},
	{
		clubName: "Matrix Berlin",
		url: "https://www.matrix-berlin.de/party-in-berlin/",
		loadMoreSelector: null,
		singleEventSelector: ".mb-2.mb-md-4.bg-dark.toggled-item",
		mainContentSelectors: [],
	},
	{
		clubName: "The Pearl Berlin",
		url: "https://thepearl-berlin.de/programm/",
		loadMoreSelector: null,
		singleEventSelector:
			".fusion-layout-column.fusion_builder_column.fusion-one-third",
		mainContentSelectors: [],
	},
	{
		clubName: "Gretchen Berlin",
		url: "https://www.gretchen-club.de/",
		loadMoreSelector: null,
		singleEventSelector: "#main .gig",
		mainContentSelectors: [],
	},
	{
		clubName: "Duncker Club",
		url: "https://www.dunckerclub.de/start.html",
		loadMoreSelector: null,
		singleEventSelector: ".tablereihe",
		mainContentSelectors: [],
	},
	{
		clubName: "Ritter Butzke",
		url: "https://club.ritterbutzke.com/events/",
		loadMoreSelector: null,
		singleEventSelector: ".column.col-xs-6.col-4.next-item",
		mainContentSelectors: [],
	},
	{
		clubName: "Arena Berlin",
		url: "https://www.arena.berlin/veranstaltungen/",
		loadMoreSelector: null,
		singleEventSelector: ".even-list-wrapper",
		mainContentSelectors: [],
	},
	{
		clubName: "Metropol Berlin",
		url: "https://metropol-berlin.de/events",
		loadMoreSelector: null,
		singleEventSelector: ".more.hide-on-mobile",
		mainContentSelectors: [".grid-60.tablet-grid-60.event-info"],
	},
	{
		clubName: "Hypersoft",
		url: "https://hypersoft.cc/",
		loadMoreSelector: null,
		singleEventSelector: "[grid-col='x12']",
		mainContentSelectors: [],
	},
	{
		clubName: "Maxxim Berlin",
		url: "https://www.maxxim-berlin.de/partys",
		loadMoreSelector: null,
		singleEventSelector: "ul.tfCiE0 li",
		mainContentSelectors: [],
	},
	{
		clubName: "Paloma Bar",
		url: "https://palomabar.de/programm.php",
		loadMoreSelector: null,
		singleEventSelector:
			"[style='border-bottom:1px solid #cccccc; padding-left:4px; font-size:14px;']",
		mainContentSelectors: [],
	},
	{
		clubName: "Spindler & Klatt",
		url: "https://spindlerklatt.com/de/club/",
		loadMoreSelector: null,
		singleEventSelector: "#wrapper .row",
		mainContentSelectors: [],
	},
	{
		clubName: "Badehaus Berlin",
		url: "https://badehaus-berlin.com/events/",
		loadMoreSelector: null,
		singleEventSelector: ".em-list.em-events-list.size-large div",
		mainContentSelectors: [],
	},
	{
		clubName: "Astra Kulturhaus",
		url: "https://www.astra-berlin.de/",
		loadMoreSelector: null,
		singleEventSelector: ".page-content article",
		mainContentSelectors: [],
	},
	{
		clubName: "Lido Berlin",
		url: "https://www.lido-berlin.de/",
		loadMoreSelector: null,
		singleEventSelector: ".event-list article",
		mainContentSelectors: [],
	},
	{
		clubName: "Hafenbar Berlin",
		url: "https://www.hafenbar-berlin.de/",
		loadMoreSelector: null,
		singleEventSelector: ".fusion-posts-container article",
		mainContentSelectors: [],
	},
	{
		clubName: "Weekend Club",
		url: "https://www.weekendclub.berlin/events",
		loadMoreSelector: null,
		singleEventSelector: ".eventlist-column-thumbnail.content-fill",
		mainContentSelectors: [".Main-content article"],
	},
	{
		clubName: "Soda Club Berlin",
		url: "https://www.soda-berlin.de/events",
		loadMoreSelector: null,
		singleEventSelector: ".rn-card.box-card-style-default.h-100",
		mainContentSelectors: [".rn-service-area.rn-section-gap"],
	},
	{
		clubName: "Loophole",
		url: "https://loophole.berlin/",
		loadMoreSelector: null,
		singleEventSelector: ".loop-container div",
		mainContentSelectors: [],
	},
	{
		clubName: "Klunkerkranich",
		url: "http://klunkerkranich.org/",
		loadMoreSelector: null,
		singleEventSelector: ".c-more-section article",
		mainContentSelectors: [],
	},
	{
		clubName: "Schokoladen",
		url: "https://www.schokoladen-mitte.de/",
		loadMoreSelector: null,
		singleEventSelector: ".event.col-12",
		mainContentSelectors: [],
	},
	{
		clubName: "Tausend",
		url: "http://tausendberlin.com/music/",
		loadMoreSelector: null,
		singleEventSelector: ".music-blog.music-col",
		mainContentSelectors: [],
	},
	{
		clubName: "Lemke",
		url: "https://www.lemke.berlin/news/",
		loadMoreSelector: ".cmplz-btn.cmplz-accept.cc-allow.cc-btn",
		singleEventSelector: ".et_pb_salvattore_content .column",
		mainContentSelectors: [],
	},
	{
		clubName: "Suprise Club Berlin",
		url: "https://surprise-berlin.de/events-programs.php",
		loadMoreSelector: null,
		singleEventSelector: ".every-event-displayed",
		mainContentSelectors: [],
	},
	{
		clubName: "Sage Club",
		url: "https://www.sage-club.de/",
		loadMoreSelector: null,
		singleEventSelector: "#sage-events-liste .event",
		mainContentSelectors: [],
	},
	{
		clubName: "Avenue Club",
		url: "https://www.avenue-club-berlin.com/events.html",
		loadMoreSelector: null,
		singleEventSelector: ".mod_newslist.events.block div",
		mainContentSelectors: [],
	},
	{
		clubName: "mbia",
		url: "https://www.m-bia.de/",
		loadMoreSelector: null,
		singleEventSelector: "#content article",
		mainContentSelectors: [],
	},
	{
		clubName: "Watergate",
		url: "http://water-gate.de/",
		loadMoreSelector: null,
		singleEventSelector: "#carousel-no1b .row",
		mainContentSelectors: [],
	},
	{
		clubName: "Aseven Club",
		url: "https://widgets.sociablekit.com/eventbrite-events/iframe/99796",
		loadMoreSelector: null,
		singleEventSelector: ".grid-facebook-event .event-details",
		mainContentSelectors: [],
	},
	{
		clubName: "Kater Blau",
		url: "https://www.katerblau.de/",
		loadMoreSelector: null,
		singleEventSelector: "#programm .container .type-tribe_events",
		mainContentSelectors: [],
	},
];

export default berlin;
