const cologne = [
	{
		clubName: "Sonic Ballroom",
		url: "https://www.sonic-ballroom.de/index.php/parties",
		loadMoreSelector: null,
		singleEventSelector: ".ccm-block-page-list-page-entry",
		mainContentSelectors: [],
	},
	{
		clubName: "Flamingo Royal",
		url: "https://www.flamingo-royal.com/#events",
		loadMoreSelector: null,
		singleEventSelector: ".swiper-container .event-card-component",
		mainContentSelectors: [".event-content-wrapper", ".description-wrapper"],
	},
	{
		clubName: "Elektroküche",
		url: "https://www.regioactive.de/location/koeln/elektrokueche-lSQg6KWpm6.html",
		loadMoreSelector: ".acceptall",
		singleEventSelector: ".article-title",
		mainContentSelectors: [],
	},
	{
		clubName: "Odonien",
		url: "https://m.odonien.de/events/",
		loadMoreSelector: null,
		singleEventSelector: ".mobileventwrapper",
		mainContentSelectors: [".container"],
	},
	{
		clubName: "Die Halle Tor 2",
		url: "https://www.diehalletor2.org/club/eventkalender/",
		loadMoreSelector: "#cookie-settings-all",
		singleEventSelector: "div#content_area .j-module.n.j-hgrid",
		mainContentSelectors: [],
	},
	{
		clubName: "Gebäude 9",
		url: "https://www.gebaeude9.de/vorschau.html",
		loadMoreSelector: null,
		singleEventSelector: "table#Table1 tr",
		mainContentSelectors: [],
	},
	{
		clubName: "Vanity",
		url: "https://vanity.cc/",
		loadMoreSelector: ".ecs-load-more-button",
		singleEventSelector:
			"div.elementor-element.elementor-element-32807a0.elementor-widget.elementor-widget-image .elementor-widget-container a",
		mainContentSelectors: ["div.ast-container"],
	},
	{
		clubName: "MTC",
		url: "https://www-mtc-cologne-de.filesusr.com/html/772350_35faaa635cb85df999539d10ac09eed3.html",
		loadMoreSelector: null,
		singleEventSelector: ".calendar-list-event",
		mainContentSelectors: [],
	},
	{
		clubName: "Veedel Club",
		url: "https://veedel-club.de/#events",
		loadMoreSelector: null,
		singleEventSelector: ".container.mx-auto.relative .pb-8",
		mainContentSelectors: ["main"],
	},
	{
		clubName: "Helios 37",
		url: "https://www.helios37.de/shows",
		loadMoreSelector: null,
		singleEventSelector: "[data-hook='event-list-item']",
		mainContentSelectors: [],
	},
	{
		clubName: "Club Diamonds",
		url: "https://club-diamonds.de/events/",
		loadMoreSelector: null,
		singleEventSelector: ".tour-dates.current-dates .group",
		mainContentSelectors: [],
	},
	{
		clubName: "Kantine",
		url: "https://kantine.com/eventliste/",
		loadMoreSelector: ".cmplz-accept",
		singleEventSelector: ".decm-events-details",
		mainContentSelectors: [],
	},
	{
		clubName: "Live Music Hall",
		url: "https://www.livemusichall.de/event",
		loadMoreSelector: ".mQxxMq.bqbmwD.Pg7AcP.KiIMJv",
		singleEventSelector: "li.LFRKo9",
		mainContentSelectors: [],
	},
	{
		clubName: "Bootshaus",
		url: "https://bootshaus.tv/events/",
		loadMoreSelector: "[data-cookiefirst-action='accept']",
		loadMoreSelector2: ".popup-close",
		singleEventSelector: ".upcoming-item.list.custom-btn",
		mainContentSelectors: [".content-section"],
	},
	{
		clubName: "Einundfünfzig",
		url: "https://einundfuenfzig.com/",
		loadMoreSelector: null,
		singleEventSelector: ".brick-content",
		mainContentSelectors: [],
	},
	{
		clubName: "Gloria",
		url: "https://gloria.koeln/programm",
		loadMoreSelector: null,
		singleEventSelector: ".list-dates .row",
		mainContentSelectors: [],
	},
	{
		clubName: "Carlswerk Victoria",
		url: "https://carlswerk-victoria.de/programm",
		loadMoreSelector: null,
		singleEventSelector: ".sc-bYoBSM.dRfMxR",
		mainContentSelectors: [],
	},
	{
		clubName: "King Georg",
		url: "https://kinggeorg.de/programm/",
		loadMoreSelector: null,
		singleEventSelector: ".event .calendar-entry",
		mainContentSelectors: [],
	},
	{
		clubName: "Die Kunstbar",
		url: "https://diekunstbar.de/die-termine/",
		loadMoreSelector: null,
		singleEventSelector: ".event_listing",
		mainContentSelectors: [".the_content_wrapper"],
	},
	{
		clubName: "Lost Level",
		url: "https://lostlevel.bar/events/",
		loadMoreSelector: null,
		singleEventSelector: ".desc_trig_outter",
		mainContentSelectors: [
			".eventon_list_event.evo_eventtop.scheduled.event.no_et",
		],
	},
	{
		clubName: "Die Wohngemeinschaft",
		url: "https://www.die-wohngemeinschaft.net/theater/veranstaltungen/",
		loadMoreSelector: "[data-full-consent='true']",
		singleEventSelector: ".col-sm-6.col-md-4",
		mainContentSelectors: [
			"div.container.row-post-height.event-single-content",
		],
	},
	{
		clubName: "Club Bahnhof Ehrenfeld",
		url: "https://www.clubbahnhofehrenfeld.de/events",
		loadMoreSelector: null,
		singleEventSelector: "article",
		mainContentSelectors: ["article"],
	},
	{
		clubName: "Tsunami Club",
		url: "https://tsunami-club.de/parties/",
		loadMoreSelector: null,
		singleEventSelector: ".tc-event-tile",
		mainContentSelectors: [],
	},
	{
		clubName: "Quater 1",
		url: "https://www.quater1.de/partys/",
		loadMoreSelector: "._brlbs-accept",
		singleEventSelector: ".fusion-events-post",
		mainContentSelectors: ["#main"],
	},
	{
		clubName: "Zum Scheuen Reh",
		url: "https://zum-scheuen-reh.de/programm/",
		loadMoreSelector: null,
		singleEventSelector: ".ecs-event-list li",
		mainContentSelectors: [],
	},
	{
		clubName: "Blue Shell",
		url: "https://www.blue-shell.de/programm",
		loadMoreSelector: null,
		singleEventSelector: "[data-hook='ev-rsvp-button']",
		mainContentSelectors: ["#PAGES_CONTAINER"],
	},
	{
		clubName: "Beer Pong Bar",
		url: "https://beerpongbar-koeln.de/events-2/",
		loadMoreSelector: null,
		singleEventSelector: ".mep_list_event_details",
		mainContentSelectors: [],
	},
	{
		clubName: "Das Ding",
		url: "https://www.dingzone.de/wp-ding/das-volle-programm/",
	},
	{
		clubName: "Mio Club",
		url: "https://www.mioclub.de/",
	},
	{
		clubName: "Cent Club",
		url: "https://centclub.de/#partys",
	},
	{
		clubName: "roonburg",
		url: "https://roonburg.de/",
	},
	{
		clubName: "gewoelbe",
		url: "https://www.gewoelbe.club/",
	},
	{
		clubName: "artheater",
		url: "https://artheater.de/",
	},
	{
		clubName: "stadtgarten",
		url: "https://www.stadtgarten.de/programm",
	},
	{
		clubName: "barinton",
		url: "https://barinton.com/events/",
	},
	{
		clubName: "autonomes zentrum",
		url: "https://az-koeln.org/events/",
	},
	{
		clubName: "bumann und sohn",
		url: "https://www.bumannundsohn.de/programm-2025",
	},
	{
		clubName: "zimmermanns",
		url: "https://zimmermanns.koeln/",
	},
	{
		clubName: "ursprung",
		url: "https://ursprung-fi.de/kalender/",
	},
	{
		clubName: "trafic",
		url: "https://www.club-trafic.de/koeln-party",
	},
	{
		clubName: "rhein roxy",
		url: "https://rhein-roxy.de/events",
	},
	{
		clubName: "altes pfandhaus",
		url: "https://altes-pfandhaus.de/programm/",
	},
	{
		clubName: "palladium",
		url: "https://www.palladium-koeln.de/programm/",
	},
];

export default cologne;
