export const musicTags = [
  { tag: 'Pop', spellings: ['Pop', 'PopMusic', 'PopularMusic', 'Top40',] },
  { tag: 'Rock', spellings: ['Rock', 'RockMusic', 'ClassicRock', 'HardRock'] },
  { tag: 'Hip Hop', spellings: ['HipHop', 'Rap', 'Rapper'] },
  { tag: 'R&B', spellings: ['RnB', 'R&B', 'RandB', 'RhythmAndBlues'] },
  { tag: 'Country', spellings: ['Country', 'CountryMusic'] },
  { tag: 'Electronic', spellings: ['Electronic', 'Electronica', 'EDM', 'Techno', 'house'] },
  { tag: 'Jazz', spellings: ['Jazz', 'Jazzy'] },
  { tag: 'Blues', spellings: ['Blues', 'Bluesy'] },
  { tag: 'Reggae', spellings: ['Reggae', 'Reggaeton'] },
  { tag: 'Metal', spellings: ['Metal', 'HeavyMetal', 'Thrash'] },
  { tag: 'Folk', spellings: ['Folk', 'FolkMusic'] },
  { tag: 'Indie', spellings: ['Indie', 'IndieRock'] },
  { tag: 'Punk', spellings: ['Punk', 'PunkRock'] },
  { tag: 'Dance', spellings: ['Dance', 'DanceMusic', 'Club'] },
  { tag: 'Alternative', spellings: ['Alternative', 'AltRock'] },
  { tag: 'Soul', spellings: ['Soul', 'SoulMusic', 'NeoSoul'] },
  { tag: 'Gospel', spellings: ['Gospel', 'GospelMusic'] },
  { tag: 'Techno', spellings: ['Techno', 'TechnoMusic'] },
  { tag: 'Trance', spellings: ['Trance', 'TranceMusic'] },
  { tag: 'Ska', spellings: ['Ska', 'SkaMusic'] },
  { tag: 'Disco', spellings: ['Disco', 'DiscoMusic'] },
  { tag: 'Funk', spellings: ['Funk', 'Funky', 'FunkyMusic'] },
  { tag: 'New Age', spellings: ['NewAge', 'Newage', 'NewAgeMusic'] },
  { tag: 'World', spellings: ['World', 'WorldMusic', 'EthnicMusic'] },
  { tag: 'Acoustic', spellings: ['Acoustic', 'AcousticMusic', 'Unplugged'] },
  { tag: 'Trap', spellings: ['Trap', 'TrapMusic'] },
  { tag: 'Dubstep', spellings: ['Dubstep', 'DubstepMusic'] },
  { tag: 'Grime', spellings: ['Grime', 'GrimeMusic'] },
  { tag: 'Hardcore', spellings: ['Hardcore', 'HardcoreMusic'] },
  { tag: 'Drum and Bass', spellings: ['DrumAndBass', 'DnB', 'DnBMusic', 'D&b'] },
  { tag: 'Ambient', spellings: ['Ambient', 'AmbientMusic'] },
  { tag: 'Experimental', spellings: ['Experimental', 'ExperimentalMusic'] }
];